[package]
name = "m07"
edition = "2024"

[[bin]]
name = "rstore-cli"
path = "src/main.rs"

[dependencies]
m00 = { workspace = true }
m01 = { workspace = true }
m02 = { workspace = true }
m03 = { workspace = true }
m05 = { workspace = true }
m06 = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
