#!/bin/bash
# Verifier dependencies are baked into environment/Dockerfile; nothing is installed here.
set -uo pipefail

mkdir -p /logs/verifier

# Fail loudly rather than silently scoring zero if the image has no WORKDIR set.
if [ "$PWD" = "/" ]; then
    echo "Error: No working directory set. Set a WORKDIR in the Dockerfile."
    echo 0 > /logs/verifier/reward.txt
    exit 0
fi

# The harness owns the build. The crate manifest, the build recipe and the launcher all go
# back to the way they shipped, any earlier artefact is thrown away, and the binary exercised
# below is compiled here out of whatever Rust is sitting in /app/src. A hand-placed binary, a
# gutted recipe, or a launcher rewritten to be the implementation itself therefore cannot
# stand in for the agent's own source.
cat > /app/Cargo.toml <<'CARGO_EOF'
[package]
name = "kxtool"
version = "1.0.0"
edition = "2021"
publish = false

[[bin]]
name = "kxtool"
path = "src/main.rs"

[dependencies]

[profile.release]
opt-level = 2
CARGO_EOF

cat > /app/Cargo.lock <<'LOCK_EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "kxtool"
version = "1.0.0"
LOCK_EOF

cat > /app/Makefile <<'MAKE_EOF'
CARGO ?= cargo

.PHONY: all build clean

all: build

build:
	$(CARGO) build --release --offline --locked

clean:
	$(CARGO) clean
MAKE_EOF

mkdir -p /app/bin
cat > /app/bin/kxtool <<'LAUNCH_EOF'
#!/bin/sh
# Launcher for the workbench binary. `make build` in /app populates target/release/kxtool.
set -e

BIN=/app/target/release/kxtool

if [ ! -x "$BIN" ]; then
    echo "kxtool: $BIN is missing; run 'make build' in /app" >&2
    exit 70
fi

exec "$BIN" "$@"
LAUNCH_EOF
chmod 0755 /app/bin/kxtool

rm -f /app/build.rs
rm -rf /app/target
cd /app && cargo build --release --offline --locked >/tmp/kxtool-build.log 2>&1 || cat /tmp/kxtool-build.log
chmod -R a+rX /app/bin 2>/dev/null || true
chmod -R a+rX /app/target/release 2>/dev/null || true

# Run from /tests (a read-only mount the agent cannot write) with PYTHONSAFEPATH so the
# working directory is never placed on sys.path.
cd /tests
PYTHONSAFEPATH=1 PYTHONDONTWRITEBYTECODE=1 python3 -m pytest -c /dev/null --confcutdir=/tests -p no:cacheprovider --ctrf /logs/verifier/ctrf.json /tests/test_outputs.py -rA
rc=$?
if [ "$rc" -eq 0 ]; then
  echo 1 > /logs/verifier/reward.txt
else
  echo 0 > /logs/verifier/reward.txt
fi
