[package]
name = "m06"
edition = "2024"

[dependencies]
m00 = { workspace = true }
m01 = { workspace = true }
m02 = { workspace = true }
m03 = { workspace = true }
m04 = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
