frr version 8.4.4
frr defaults traditional
hostname edge-ams-01
service integrated-vtysh-config
!
ip prefix-list INTENDED-V4 seq 10 permit 193.0.0.0/21
ipv6 prefix-list INTENDED-V6 seq 10 permit 2001:67c:2e8::/48
!
route-map IN-PRIMARY permit 10
 set local-preference 200
exit
!
route-map IN-STANDBY permit 10
 set local-preference 100
exit
!
route-map OUT-PRIMARY permit 10
 match ip address prefix-list INTENDED-V4
exit
!
route-map OUT-PRIMARY permit 20
 match ipv6 address prefix-list INTENDED-V6
exit
!
route-map OUT-PRIMARY deny 100
exit
!
router bgp 3333
 bgp router-id 192.0.2.10
 no bgp ebgp-requires-policy
 neighbor 192.0.2.2 remote-as 64501
 neighbor 192.0.2.6 remote-as 64502
 neighbor 2001:db8:10::2 remote-as 64501
 neighbor 2001:db8:20::2 remote-as 64502
 !
 address-family ipv4 unicast
  network 193.0.0.0/21
  neighbor 192.0.2.2 route-map IN-PRIMARY in
  neighbor 192.0.2.2 route-map OUT-PRIMARY out
  neighbor 192.0.2.6 route-map IN-STANDBY in
 exit-address-family
 !
 address-family ipv6 unicast
  network 2001:67c:2e8::/48
  neighbor 2001:db8:10::2 activate
  neighbor 2001:db8:10::2 route-map IN-PRIMARY in
  neighbor 2001:db8:10::2 route-map OUT-PRIMARY out
  neighbor 2001:db8:20::2 activate
  neighbor 2001:db8:20::2 route-map IN-STANDBY in
 exit-address-family
exit
!
end
