[workspace]
resolver = "2"
members = [
    "pkg/m00",
    "pkg/m01",
    "pkg/m02",
    "pkg/m03",
    "pkg/m04",
    "pkg/m05",
    "pkg/m06",
    "pkg/m07",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
hex = "0.4.3"
rand = "0.9.1"
rand_chacha = "0.9.0"
rusqlite = { version = "0.34.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
tempfile = "3.20.0"
thiserror = "2.0.12"
toml = "0.8.22"
tracing = "0.1.41"
walkdir = "2.5.0"
m00 = { path = "pkg/m00" }
m01 = { path = "pkg/m01" }
m02 = { path = "pkg/m02" }
m03 = { path = "pkg/m03" }
m04 = { path = "pkg/m04" }
m05 = { path = "pkg/m05" }
m06 = { path = "pkg/m06" }
m07 = { path = "pkg/m07" }
