import { escapeMakePath } from '../util/escaping.mjs';

function buildFilterGraph(filters) {
  if (!filters.length) return 'null';
  return filters
    .slice()
    .sort((a, b) => (a.phase - b.phase) || (a.sequence - b.sequence))
    .map((f) => (f.args ? `${f.name}=${f.args}` : f.name))
    .join(',');
}

/** Shell-quoted path whose Make variable root is expanded by Make first. */
function makeShellPath(rootVar, relativePath) {
  const escaped = String(relativePath)
    .replace(/'/g, `'\\''`)
    .replace(/\$/g, '$$$$'); // literal $ -> $$ for Make
  return `'$(${rootVar})/${escaped}'`;
}

function recipeForJob(job, assetRel) {
  const outFile = job.output.filename;
  const input = makeShellPath('ASSET_ROOT', assetRel);
  const output = makeShellPath('OUTPUT_ROOT', outFile);
  const cache = makeShellPath('CACHE_ROOT', `${job.cache_key}.done`);
  const vf = buildFilterGraph(job.filters).replace(/\$/g, '$$$$');
  const parts = [
    'mkdir',
    '-p',
    `$$(dirname ${output})`,
    `$$(dirname ${cache})`,
    '&&',
    '$(FFMPEG)',
    '-y',
    '-i',
    input,
  ];
  if (job.output.video_codec) {
    parts.push('-vf', `'${vf}'`);
    parts.push('-c:v', job.output.video_codec);
    if (job.output.pixel_format) parts.push('-pix_fmt', job.output.pixel_format);
    if (job.output.video_profile != null) parts.push('-profile:v', String(job.output.video_profile));
    if (job.output.video_tag) parts.push('-tag:v', job.output.video_tag);
  } else {
    parts.push('-vn');
  }
  if (job.output.audio_codec) {
    parts.push('-c:a', job.output.audio_codec);
  }
  parts.push(output);
  parts.push(';', 'touch', cache);
  return parts.join(' ');
}

export function renderMakefile({ buildPlan, inventory }) {
  const lines = [];
  lines.push('# Generated by aurora-build — do not edit');
  lines.push('ASSET_ROOT ?= /assets');
  lines.push('OUTPUT_ROOT ?= /output');
  lines.push('CACHE_ROOT ?= /cache');
  lines.push('FFMPEG ?= ffmpeg');
  lines.push('');
  const targets = buildPlan.jobs.map((j) => escapeMakePath(j.output.filename));
  lines.push('.PHONY: all');
  lines.push(`all: ${targets.join(' ')}`);
  lines.push('');

  const assetById = new Map(inventory.assets.map((a) => [a.id, a]));
  for (const job of buildPlan.jobs) {
    const asset = assetById.get(job.asset_id);
    const prereqFixed = `$(ASSET_ROOT)/${escapeMakePath(asset.relative_path)}`;
    const target = escapeMakePath(job.output.filename);
    lines.push(`${target}: ${prereqFixed}`);
    lines.push(`\t${recipeForJob(job, asset.relative_path)}`);
    lines.push('');
  }
  return lines.join('\n');
}
