[package]
name = "m03"
version.workspace = true
edition.workspace = true

[dependencies]
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
m01-seal = { path = "../m01-seal" }
m02-cipher = { path = "../m02-cipher" }
